export const HIDDEN_KEYMAP = [
  "#",
  "&",
  ")",
  "R",
  "U",
  "A",
  "F",
  "K",
  "X",
  "N",
  "M",
];
export const ORIGIN_KEYMAP = ["!", "@", "#", "$", "%", "^", "&", "*", "(", ")"];
export const WHITE_KEYMAP = [
  { key: "1", code: "Digit1", displayKey: "1" },
  { key: "2", code: "Digit2", displayKey: "2" },
  { key: "3", code: "Digit3", displayKey: "3" },
  { key: "4", code: "Digit4", displayKey: "4" },
  { key: "5", code: "Digit5", displayKey: "5" },
  { key: "6", code: "Digit6", displayKey: "6" },
  { key: "7", code: "Digit7", displayKey: "7" },
  { key: "8", code: "Digit8", displayKey: "8" },
  { key: "9", code: "Digit9", displayKey: "9" },
  { key: "0", code: "Digit0", displayKey: "0" },
  { key: "q", code: "Keyq", displayKey: "q" },
  { key: "w", code: "Keyw", displayKey: "w" },
  { key: "e", code: "Keye", displayKey: "e" },
  { key: "r", code: "Keyr", displayKey: "r" },
  { key: "t", code: "Keyt", displayKey: "t" },
  { key: "y", code: "Keyy", displayKey: "y" },
  { key: "u", code: "Keyu", displayKey: "u" },
  { key: "i", code: "Keyi", displayKey: "i" },
  { key: "o", code: "Keyo", displayKey: "o" },
  { key: "p", code: "Keyp", displayKey: "p" },
  { key: "a", code: "Keya", displayKey: "a" },
  { key: "s", code: "Keys", displayKey: "s" },
  { key: "d", code: "Keyd", displayKey: "d" },
  { key: "f", code: "Keyf", displayKey: "f" },
  { key: "g", code: "Keyg", displayKey: "g" },
  { key: "h", code: "Keyh", displayKey: "h" },
  { key: "j", code: "Keyj", displayKey: "j" },
  { key: "k", code: "Keyk", displayKey: "k" },
  { key: "l", code: "Keyl", displayKey: "l" },
  { key: "z", code: "Keyz", displayKey: "z" },
  { key: "x", code: "Keyx", displayKey: "x" },
  { key: "c", code: "Keyc", displayKey: "c" },
  { key: "v", code: "Keyv", displayKey: "v" },
  { key: "b", code: "Keyb", displayKey: "b" },
  { key: "n", code: "Keyn", displayKey: "n" },
  { key: "m", code: "Keym", displayKey: "m" },
];

export const BLACK_KEYMAP = [
  { key: "!", code: "Digit1-1", displayKey: "1" },
  { key: "@", code: "Digit2-2", displayKey: "2" },
  { key: "#", code: "Digit3-3", displayKey: "3" },
  { key: "$", code: "Digit4-4", displayKey: "4" },
  { key: "%", code: "Digit5-5", displayKey: "5" },
  { key: "^", code: "Digit6-6", displayKey: "6" },
  { key: "&", code: "Digit7-7", displayKey: "7" },
  { key: "*", code: "Digit8-8", displayKey: "8" },
  { key: "(", code: "Digit9-9", displayKey: "9" },
  { key: ")", code: "Digit0-0", displayKey: "0" },
  { key: "Q", code: "KeyQ-Q", displayKey: "Q" },
  { key: "W", code: "KeyW-W", displayKey: "W" },
  { key: "E", code: "KeyE-E", displayKey: "E" },
  { key: "R", code: "KeyR-R", displayKey: "R" },
  { key: "T", code: "KeyT-T", displayKey: "T" },
  { key: "Y", code: "KeyY-Y", displayKey: "Y" },
  { key: "U", code: "KeyU-U", displayKey: "U" },
  { key: "I", code: "KeyI-I", displayKey: "I" },
  { key: "O", code: "KeyO-O", displayKey: "O" },
  { key: "P", code: "KeyP-P", displayKey: "P" },
  { key: "A", code: "KeyA-A", displayKey: "A" },
  { key: "S", code: "KeyS-S", displayKey: "S" },
  { key: "D", code: "KeyD-D", displayKey: "D" },
  { key: "F", code: "KeyF-F", displayKey: "F" },
  { key: "G", code: "KeyG-G", displayKey: "G" },
  { key: "H", code: "KeyH-H", displayKey: "H" },
  { key: "J", code: "KeyJ-J", displayKey: "J" },
  { key: "K", code: "KeyK-K", displayKey: "K" },
  { key: "L", code: "KeyL-L", displayKey: "L" },
  { key: "Z", code: "KeyZ-Z", displayKey: "Z" },
  { key: "X", code: "KeyX-X", displayKey: "X" },
  { key: "C", code: "KeyC-C", displayKey: "C" },
  { key: "V", code: "KeyV-V", displayKey: "V" },
  { key: "B", code: "KeyB-B", displayKey: "B" },
  { key: "N", code: "KeyN-N", displayKey: "N" },
  { key: "M", code: "KeyM-M", displayKey: "M" },
];
